version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-poc
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db-poc
    environment:
      POSTGRES_PASSWORD: pro
      POSTGRES_USER: pro
      POSTGRES_DB: poc
    ports:
      - 5432:5432
    depends_on:
      - config-server
  config-server:
    build: ./ConfigServer/.
    image: srpoe/configserverpoc
    ports:
      - 8888:8888

