FROM openjdk:8-jdk-alpine

WORKDIR /poc-api-build

COPY . /poc-api-build

RUN ls -al

RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline

RUN ./mvnw package

WORKDIR /poc-api

RUN cp /poc-api-build/target/*.jar /poc-api/app.jar

RUN rm -rf /poc-api-build

RUN ls -al

ENTRYPOINT [ "java", "-jar", "/poc-api/app.jar" ]