security.basic.enable: false
management.security.enabled: false

server:
  port: 8888

spring:
  application:
    name: myConfigServer
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/LuizFrra/PoC-Probate
          searchPaths: configProperties

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/
