server:
  port: 8541

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://192.168.0.16:5432/auth
    username: pro
    password: pro

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/