server:
  port: 9090

probate:
  youtube:
    path-save:
      windows: L:\\Windows Folders\\Desktop\\PoC-Probate
      linux: /home

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/poc
    username: pro
    password: pro
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns:  true
    listener:
      simple:
        prefetch: 1
      direct:
        prefetch: 1

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/
