server:
  port: 9090

probate:
  youtube:
    path-save:
      windows: L:\\Windows Folders\\Desktop\\PoC-Probate
      linux: /home

management:
  endpoints:
    web:
      exposure:
        include: *

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://192.168.0.16:5432/poc
    username: pro
    password: pro
  rabbitmq:
    host: 192.168.0.16
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns:  true
    listener:
      simple:
        prefetch: 1
      direct:
        prefetch: 1